# Define a reusable macro function to clean files passed as an argument
# $(1) contains space-separated list of files to remove
define clean_body
	@echo "Invoking clean at TIMESTAMP=$(TIMESTAMP)"
	@rm -f $(1)
endef
